# vim: set ft=Yaml ts=2

# General
site_name: M42PL

# Navigation
nav:
  - "Home": index.md
  - "Quick start":
    - "Installation": "quickstart/installation.md"
    - "First steps": "quickstart/firststeps.md"
  - "Commands index": "https://jpclipffel.github.io/m42pl-commands"
  - "Run pipelines":
    - "Overview": "mains/index.md"
    - "REPL (interactive)": "mains/repl2.md"
    - "Script": "mains/run.md"
    - "Grammar debug": "mains/grammar.md"
    - "Parsing debug": "mains/parse.md"
  - "Fields":
    - "Overview": "fields/index.md"
    - "Literal": "fields/literal.md"
    - "Path": "fields/path.md"
    - "Evaluated": "fields/eval.md"
    - "JsonPath": "fields/jsonpath.md"
    - "Pipeline": "fields/pipe.md"
  - "Components":
    - "Overview": "components/index.md"
    - "Core": "components/core.md"
    - "Commands": "components/commands.md"
    - "KVStores": "components/kvstores.md"
    - "Encoders": "components/encoders.md"
    - "Dispatchers": "components/dispatchers.md"

# Source repository
repo_url: https://github.com/jpclipffel/m42pl-core
repo_name: jpclipffel/m42pl-core
edit_uri: tree/main/docs/docs
src_uri: tree/main/docs/docs

# Markdown extensions
markdown_extensions:
  - admonition

# Theme configuration
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: "assets/Logo - Text - White.png"
  favicon: "assets/Logo - Text - White.png"
